on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
      
        - name: Setup Python
          uses: actions/setup-python@v2.1.4
          with:
            python-version: 3.7
        - run: |
            az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.31-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2 -y  
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/stevenystest2021:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/stevenystest2021:${{ github.sha }}
#       new code here...
#        - name: 'Run Scripts on Azure ML Computes'
        - run: |
            az config set defaults.workspace=stevenys-wmtacr-demo-ws
            az config set defaults.group=stevenys-wmtacr-demo-rg
            az config set defaults.location=westus
            az account set -s ea1dc7d2-92ee-4134-9128-8c0a0341f8ca
            az ml job create --file hello_python_job.yml

       
 
          
            
      


#        - name: 'Deploy to Azure Container Instances'
#          uses: 'azure/aci-deploy@v1'
#          with:
#            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
#            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
#            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
#            registry-username: ${{ secrets.REGISTRY_USERNAME }}
#            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
#            name: aci-sampleapp
#            location: 'west us'
